-------------------------------------------------------------------------------
Test set: com.syos.application.commands.user.LoginCommandTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.023 s <<< FAILURE! -- in com.syos.application.commands.user.LoginCommandTest
com.syos.application.commands.user.LoginCommandTest.should_handle_already_logged_in_user_and_offer_logout_option -- Time elapsed: 0.015 s <<< FAILURE!
Wanted but not invoked:
presenter.showInfo(
    "Already logged in as: currentuser"
);
-> at com.syos.infrastructure.ui.presenters.UserPresenter.showInfo(UserPresenter.java:35)

However, there were exactly 2 interactions with this mock:
presenter.showHeader("User Login");
-> at com.syos.application.commands.user.LoginCommand.execute(LoginCommand.java:42)

presenter.showLoginSuccess(
    Mock for User, hashCode: 1454136448
);
-> at com.syos.application.commands.user.LoginCommand.execute(LoginCommand.java:61)


	at com.syos.infrastructure.ui.presenters.UserPresenter.showInfo(UserPresenter.java:35)
	at com.syos.application.commands.user.LoginCommandTest.should_handle_already_logged_in_user_and_offer_logout_option(LoginCommandTest.java:149)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)

